server:
  port: 3000

springdoc:
  api-docs:
    path: /openapi

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/static/
  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0
  h2:
    console.enabled: true